version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=groupon
      - DB_USERNAME=root
      - DB_PASSWORD=PASSWORD
    networks:
      - groupon-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - groupon-network

  database:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD
      - MYSQL_ROOT_HOST='%'
      - MYSQL_DATABASE=groupon
      - MYSQL_USER=root
      - MYSQL_PASSWORD=PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - groupon-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    depends_on:
      - database
    networks:
      - groupon-network

networks:
  groupon-network:

volumes:
  db_data:
